#!/usr/bin/python3

import sys
import time
import signal
import RPi.GPIO as GPIO

DTR = 'TIOCM_DTR'
PIN = 7
PULSE_TIME = 0.32
MAX_TIME = 5000

def reset():
    GPIO.setup(PIN, GPIO.OUT)
    GPIO.output(PIN, GPIO.HIGH)
    time.sleep(PULSE_TIME)
    GPIO.output(PIN, GPIO.LOW)

def process():
    while True:
        text = sys.stdin.readline()
        if not text:
            return
        if DTR in text:
            print("avrdude-original: Using autoreset DTR on GPIO Pin", PIN)
            reset()

def main():
    signal.alarm(MAX_TIME)
    GPIO.setwarnings(False)  # FIXME why disable warnings? This seems unwise!
    GPIO.setmode(GPIO.BOARD)
    process()
    GPIO.cleanup()

if __name__ == '__main__':
    main()
