#!/usr/bin/python3

import sys
import time
import RPi.GPIO as GPIO

DTR = 'TIOCM_DTR'
PIN = 7
PULSE_TIME = 0.32
MAX_TIME = 5000

def reset():
    GPIO.setup(PIN, GPIO.OUT)
    GPIO.output(PIN, GPIO.HIGH)
    time.sleep(PULSE_TIME)
    GPIO.output(PIN, GPIO.LOW)

def process():
    start = time.time()
    while True:
        duration = time.time() - start
        text = sys.stdin.readline()
        if DTR in text:
            reset()
            return  # FIXME this will close stdin at exit and caused Broken Pipe errors. We should continue to act as a filter.
        elif duration > MAX_TIME:
            return

def main():
    GPIO.setwarnings(False)  # FIXME why disable warnings? This seems unwise!
    GPIO.setmode(GPIO.BOARD)
    process()
    print("avrdude-original: Using autoreset DTR on GPIO Pin", PIN)
    GPIO.cleanup()

if __name__ == '__main__':
    main()
